### ISSUE TITLE
Environment setup

### ISSUE THREAD

**Issue by alexander-myltsev** [gkossakowski/scalac-aspects#5]
Hi @gkossakowski ,

thanks for the project. I hope to speed up our project compilation from 300 to 600 LoC/s.

It seems to install a bit harder than good old SBT.

I started with aspectj in Ubuntu 14.04 repo. 

``` bash
➤  ajc -v
AspectJ Compiler 1.6.12 (DEVELOPMENT - Built: Friday Jan 27, 2012 at 13:21:56 GMT) - Eclipse Compiler 0.785_R33x, 3.3
```

I needed to make changes to your sources:

``` diff
diff --git a/scalac-aspects b/scalac-aspects
index 05425ac..9cabe50 100755
--- a/scalac-aspects
+++ b/scalac-aspects
@@ -27,8 +27,8 @@ SCALA_HOME=${SCALA_HOME:-$(findHomeOf scala)}
 [[ -n "$SCALA_HOME" ]] || die "SCALA_HOME must be set."

 SCALA_LIBS=$(mkCp $SCALA_HOME/lib/*)
-AJ_WEAVER="$ASPECTJ_HOME/lib/aspectjweaver.jar"
-AJ_RUNTIME="$ASPECTJ_HOME/lib/aspectjrt.jar"
+AJ_WEAVER="$ASPECTJ_HOME/share/java/aspectjweaver.jar"
+AJ_RUNTIME="$ASPECTJ_HOME/share/java/aspectjrt.jar"

 AJ_FILE="$1" && shift
 SCALA_ARGS=( "$@" )
```

And I get those errors:

``` bash
  ./scalac-aspects TraceSymbol.aj -DtraceSymbolIds=500,505 Foo.scala
/usr/bin/ajc -1.5 -cp /usr/share/java/aspectjrt.jar:/home/alex/apps/scala-2.11.2/bin/lib/* -outxml -outjar /tmp/scalac-aspects.9F9N7reH6s/aspects.jar TraceSymbol.aj
org.aspectj.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 15
    at org.aspectj.apache.bcel.classfile.Constant.readConstant(Constant.java:133)
    at org.aspectj.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:45)
    at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:186)
    at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
    at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:424)
    at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:376)
    at org.aspectj.weaver.World.resolveToReferenceType(World.java:485)
    at org.aspectj.weaver.World.resolve(World.java:326)
    at org.aspectj.weaver.World.resolve(World.java:236)
    at org.aspectj.weaver.bcel.BcelGenericSignatureToTypeXConverter.classTypeSignature2TypeX(BcelGenericSignatureToTypeXConverter.java:97)
    at org.aspectj.weaver.bcel.BcelGenericSignatureToTypeXConverter.classTypeSignature2TypeX(BcelGenericSignatureToTypeXConverter.java:41)
    at org.aspectj.weaver.bcel.BcelObjectType.ensureGenericSignatureUnpacked(BcelObjectType.java:810)
    at org.aspectj.weaver.bcel.BcelObjectType.getDeclaredInterfaces(BcelObjectType.java:257)
    at org.aspectj.weaver.ReferenceType.getDeclaredInterfaces(ReferenceType.java:626)
    at org.aspectj.weaver.ResolvedType.getDirectSupertypes(ResolvedType.java:82)
    at org.aspectj.weaver.ResolvedType.collectInterTypeMungers(ResolvedType.java:1374)
    at org.aspectj.weaver.ResolvedType.getInterTypeMungersIncludingSupers(ResolvedType.java:1355)
    at org.aspectj.weaver.ResolvedType.checkInterTypeMungers(ResolvedType.java:1426)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.weaveInterTypeDeclarations(AjLookupEnvironment.java:809)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.weaveInterTypeDeclarations(AjLookupEnvironment.java:652)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.createBinaryTypeFrom(AjLookupEnvironment.java:1398)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:599)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:276)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:113)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:133)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveTypesFor(BinaryTypeBinding.java:974)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.methodsBase(BinaryTypeBinding.java:957)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.methods(BinaryTypeBinding.java:1116)
    at org.aspectj.org.eclipse.jdt.internal.compiler.ast.Annotation.resolveType(Annotation.java:243)
    at org.aspectj.org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:594)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getAnnotationTagBits(SourceTypeBinding.java:741)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:623)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:451)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:629)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:392)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1024)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:268)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:181)
    at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
    at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
    at org.aspectj.tools.ajc.Main.run(Main.java:371)
    at org.aspectj.tools.ajc.Main.runMain(Main.java:248)
    at org.aspectj.tools.ajc.Main.main(Main.java:84)
/home/alex/projects/scalac-aspects/TraceSymbol.aj:2 [error] The import scala cannot be resolved
import scala.reflect.internal.Symbols.Symbol;
       ^^^^
/home/alex/projects/scalac-aspects/TraceSymbol.aj:3 [error] The import scala cannot be resolved
import scala.reflect.internal.util.Position;
       ^^^^
/home/alex/projects/scalac-aspects/TraceSymbol.aj:4 [error] The import scala cannot be resolved
import scala.reflect.internal.Names.Name;
       ^^^^
/home/alex/projects/scalac-aspects/TraceSymbol.aj:23 [error] scala cannot be resolved to a type
private boolean shouldTrace(scala.reflect.internal.Symbols.Symbol s) {
                            ^^
/home/alex/projects/scalac-aspects/TraceSymbol.aj:32 [error] Symbol cannot be resolved to a type
after(Symbol self, Symbol initOwner, Position initPos, Name initName): execution(Symbol.new(..)) && args(*, initOwner, initPos, initName) && this(self) {
      ^^^
/home/alex/projects/scalac-aspects/TraceSymbol.aj:32 [error] Symbol cannot be resolved to a type
after(Symbol self, Symbol initOwner, Position initPos, Name initName): execution(Symbol.new(..)) && args(*, initOwner, initPos, initName) && this(self) {
                   ^^^
/home/alex/projects/scalac-aspects/TraceSymbol.aj:32 [error] Position cannot be resolved to a type
after(Symbol self, Symbol initOwner, Position initPos, Name initName): execution(Symbol.new(..)) && args(*, initOwner, initPos, initName) && this(self) {
                                     ^^^^^
/home/alex/projects/scalac-aspects/TraceSymbol.aj:32 [error] Name cannot be resolved to a type
after(Symbol self, Symbol initOwner, Position initPos, Name initName): execution(Symbol.new(..)) && args(*, initOwner, initPos, initName) && this(self) {
                                                       ^
org.aspectj.apache.bcel.classfile.ClassFormatException: File: 'java/lang/CharSequence.class': Invalid byte tag in constant pool: 15
    at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:192)
    at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
    at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:424)
    at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:376)
    at org.aspectj.weaver.World.resolveToReferenceType(World.java:485)
    at org.aspectj.weaver.World.resolve(World.java:326)
    at org.aspectj.weaver.World.resolve(World.java:236)
    at org.aspectj.weaver.bcel.BcelGenericSignatureToTypeXConverter.classTypeSignature2TypeX(BcelGenericSignatureToTypeXConverter.java:97)
    at org.aspectj.weaver.bcel.BcelGenericSignatureToTypeXConverter.classTypeSignature2TypeX(BcelGenericSignatureToTypeXConverter.java:41)
    at org.aspectj.weaver.bcel.BcelObjectType.ensureGenericSignatureUnpacked(BcelObjectType.java:810)
    at org.aspectj.weaver.bcel.BcelObjectType.getDeclaredInterfaces(BcelObjectType.java:257)
    at org.aspectj.weaver.ReferenceType.getDeclaredInterfaces(ReferenceType.java:626)
    at org.aspectj.weaver.ResolvedType.getDirectSupertypes(ResolvedType.java:82)
    at org.aspectj.weaver.ResolvedType.collectInterTypeMungers(ResolvedType.java:1374)
    at org.aspectj.weaver.ResolvedType.getInterTypeMungersIncludingSupers(ResolvedType.java:1355)
    at org.aspectj.weaver.ResolvedType.checkInterTypeMungers(ResolvedType.java:1426)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.weaveInterTypeDeclarations(AjLookupEnvironment.java:809)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.weaveInterTypeDeclarations(AjLookupEnvironment.java:652)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.createBinaryTypeFrom(AjLookupEnvironment.java:1398)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:599)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:276)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:113)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:133)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveTypesFor(BinaryTypeBinding.java:974)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.methodsBase(BinaryTypeBinding.java:957)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.methods(BinaryTypeBinding.java:1116)
    at org.aspectj.org.eclipse.jdt.internal.compiler.ast.Annotation.resolveType(Annotation.java:243)
    at org.aspectj.org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:594)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getAnnotationTagBits(SourceTypeBinding.java:741)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:623)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:451)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:629)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:392)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1024)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:268)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:181)
    at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
    at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
    at org.aspectj.tools.ajc.Main.run(Main.java:371)
    at org.aspectj.tools.ajc.Main.runMain(Main.java:248)
    at org.aspectj.tools.ajc.Main.main(Main.java:84)
ABORT

Exception thrown from AspectJ DEVELOPMENT

This might be logged as a bug already -- find current bugs at
  http://bugs.eclipse.org/bugs/buglist.cgi?product=AspectJ&component=Compiler

Bugs for exceptions thrown have titles File:line from the top stack, 
e.g., "SomeFile.java:243"

If you don't find the exception below in a bug, please add a new bug
at http://bugs.eclipse.org/bugs/enter_bug.cgi?product=AspectJ
To make the bug a priority, please include a test program
that can reproduce this exception.
File: 'java/lang/CharSequence.class': Invalid byte tag in constant pool: 15

when batch building BuildConfig[null] #Files=1 AopXmls=#0
File: 'java/lang/CharSequence.class': Invalid byte tag in constant pool: 15
org.aspectj.apache.bcel.classfile.ClassFormatException: File: 'java/lang/CharSequence.class': Invalid byte tag in constant pool: 15
    at org.aspectj.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:192)
    at org.aspectj.apache.bcel.classfile.ClassParser.parse(ClassParser.java:131)
    at org.aspectj.weaver.bcel.BcelWorld.lookupJavaClass(BcelWorld.java:424)
    at org.aspectj.weaver.bcel.BcelWorld.resolveDelegate(BcelWorld.java:376)
    at org.aspectj.weaver.World.resolveToReferenceType(World.java:485)
    at org.aspectj.weaver.World.resolve(World.java:326)
    at org.aspectj.weaver.World.resolve(World.java:236)
    at org.aspectj.weaver.bcel.BcelGenericSignatureToTypeXConverter.classTypeSignature2TypeX(BcelGenericSignatureToTypeXConverter.java:97)
    at org.aspectj.weaver.bcel.BcelGenericSignatureToTypeXConverter.classTypeSignature2TypeX(BcelGenericSignatureToTypeXConverter.java:41)
    at org.aspectj.weaver.bcel.BcelObjectType.ensureGenericSignatureUnpacked(BcelObjectType.java:810)
    at org.aspectj.weaver.bcel.BcelObjectType.getDeclaredInterfaces(BcelObjectType.java:257)
    at org.aspectj.weaver.ReferenceType.getDeclaredInterfaces(ReferenceType.java:626)
    at org.aspectj.weaver.ResolvedType.getDirectSupertypes(ResolvedType.java:82)
    at org.aspectj.weaver.ResolvedType.collectInterTypeMungers(ResolvedType.java:1374)
    at org.aspectj.weaver.ResolvedType.getInterTypeMungersIncludingSupers(ResolvedType.java:1355)
    at org.aspectj.weaver.ResolvedType.checkInterTypeMungers(ResolvedType.java:1426)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.weaveInterTypeDeclarations(AjLookupEnvironment.java:809)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.weaveInterTypeDeclarations(AjLookupEnvironment.java:652)
    at org.aspectj.ajdt.internal.compiler.lookup.AjLookupEnvironment.createBinaryTypeFrom(AjLookupEnvironment.java:1398)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:599)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:276)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:113)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:133)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveTypesFor(BinaryTypeBinding.java:974)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.methodsBase(BinaryTypeBinding.java:957)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.methods(BinaryTypeBinding.java:1116)
    at org.aspectj.org.eclipse.jdt.internal.compiler.ast.Annotation.resolveType(Annotation.java:243)
    at org.aspectj.org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:594)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getAnnotationTagBits(SourceTypeBinding.java:741)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:623)
    at org.aspectj.org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:451)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:629)
    at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:392)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1024)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:268)
    at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:181)
    at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
    at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
    at org.aspectj.tools.ajc.Main.run(Main.java:371)
    at org.aspectj.tools.ajc.Main.runMain(Main.java:248)
    at org.aspectj.tools.ajc.Main.main(Main.java:84)

Aug 20, 2014 4:05:36 PM org.aspectj.weaver.tools.Jdk14Trace info
INFO: Dumping to /home/alex/projects/scalac-aspects/./ajcore.20140820.160536.774.txt
```

How to fix them?

**Comment by alexander-myltsev** [comment]
I forgot to ask. Would it work for `Scala 2.11.2`?

**Comment by gkossakowski** [comment]
Hey!

I believe you need AspectJ 1.7 for errors to go away. That's what I'm using. I tested apsects with Scala 2.11.2 and it works:

```
./scalac-aspects PerUnitTiming.aj Foo.scala
/Users/grek/aspectj1.7//bin/ajc -1.5 -cp /Users/grek/aspectj1.7//lib/aspectjrt.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/akka-actor_2.11-2.3.4.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/config-1.2.1.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/jline-2.12.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-actors-2.11.0.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-actors-migration_2.11-1.1.0.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-compiler.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-continuations-library_2.11-1.0.2.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-continuations-plugin_2.11.2-1.0.2.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-library.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-parser-combinators_2.11-1.0.2.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-reflect.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-swing_2.11-1.0.1.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scala-xml_2.11-1.0.2.jar:/usr/local/Cellar/scala/2.11.2/libexec/lib/scalap-2.11.2.jar -outxml -outjar /var/folders/0k/31jh6c293n31_tjkxmk90jjh0000gn/T/scalac-aspects.XXXXXXXXXX.2eyS53fI/aspects.jar PerUnitTiming.aj
/Users/grek/scala/scalac-aspects/PerUnitTiming.aj:32 [warning] advice defined in PerUnitTiming has not been applied [Xlint:adviceDidNotMatch]

/Users/grek/scala/scalac-aspects/PerUnitTiming.aj:13 [warning] advice defined in PerUnitTiming has not been applied [Xlint:adviceDidNotMatch]


2 warnings
/usr/local/Cellar/scala/2.11.2/libexec/bin/scalac -nobootcp -J-javaagent:/Users/grek/aspectj1.7//lib/aspectjweaver.jar -toolcp /var/folders/0k/31jh6c293n31_tjkxmk90jjh0000gn/T/scalac-aspects.XXXXXXXXXX.2eyS53fI/aspects.jar -d /var/folders/0k/31jh6c293n31_tjkxmk90jjh0000gn/T/scalac-aspects.XXXXXXXXXX.2eyS53fI Foo.scala
Per-file timings (all times are in micro seconds)
Foo.scala 1731182
    parser                    156601
    namer                     225691
    packageobjects            59
    typer                     420347
    patmat                    9192
    superaccessors            6299
    extmethods                2527
    pickler                   32592
    refchecks                 113930
    uncurry                   25760
    tailcalls                 28355
    specialize                70877
    explicitouter             64411
    erasure                   333178
    posterasure               5252
    lazyvals                  8775
    lambdalift                78532
    constructors              60908
    flatten                   333
    mixin                     14659
    cleanup                   12276
    delambdafy                7311
    icode                     53317
```

**Comment by alexander-myltsev** [comment]
OK, resolved 

```
➤  ajc -v
AspectJ Compiler 1.7.3 (1.7.4 - Built: Friday Oct 25, 2013 at 15:00:26 GMT) - Eclipse Compiler 0.B79_R37x, 3.7
```

Errors are:

```
➤  ./scalac-aspects TraceSymbol.aj -DtraceSymbolIds=500,505 Foo.scala
/home/alex/apps/aspectj1.7
/home/alex/apps/aspectj1.7/bin/ajc -1.5 -cp /home/alex/apps/aspectj1.7/lib/aspectjrt.jar:/home/alex/apps/scala-2.11.2/lib/akka-actor_2.11-2.3.4.jar:/home/alex/apps/scala-2.11.2/lib/config-1.2.1.jar:/home/alex/apps/scala-2.11.2/lib/jline-2.12.jar:/home/alex/apps/scala-2.11.2/lib/scala-actors-2.11.0.jar:/home/alex/apps/scala-2.11.2/lib/scala-actors-migration_2.11-1.1.0.jar:/home/alex/apps/scala-2.11.2/lib/scala-compiler.jar:/home/alex/apps/scala-2.11.2/lib/scala-continuations-library_2.11-1.0.2.jar:/home/alex/apps/scala-2.11.2/lib/scala-continuations-plugin_2.11.2-1.0.2.jar:/home/alex/apps/scala-2.11.2/lib/scala-library.jar:/home/alex/apps/scala-2.11.2/lib/scalap-2.11.2.jar:/home/alex/apps/scala-2.11.2/lib/scala-parser-combinators_2.11-1.0.2.jar:/home/alex/apps/scala-2.11.2/lib/scala-reflect.jar:/home/alex/apps/scala-2.11.2/lib/scala-swing_2.11-1.0.1.jar:/home/alex/apps/scala-2.11.2/lib/scala-xml_2.11-1.0.2.jar -outxml -outjar /tmp/scalac-aspects.y9deqUZYxj/aspects.jar TraceSymbol.aj
/home/alex/projects/scalac-aspects/TraceSymbol.aj:1 [error] The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files
(no source information available)

1 error
```

```
➤  ./scalac-aspects PerUnitTiming.aj Foo.scala
/home/alex/apps/aspectj1.7
/home/alex/apps/aspectj1.7/bin/ajc -1.5 -cp /home/alex/apps/aspectj1.7/lib/aspectjrt.jar:/home/alex/apps/scala-2.11.2/lib/akka-actor_2.11-2.3.4.jar:/home/alex/apps/scala-2.11.2/lib/config-1.2.1.jar:/home/alex/apps/scala-2.11.2/lib/jline-2.12.jar:/home/alex/apps/scala-2.11.2/lib/scala-actors-2.11.0.jar:/home/alex/apps/scala-2.11.2/lib/scala-actors-migration_2.11-1.1.0.jar:/home/alex/apps/scala-2.11.2/lib/scala-compiler.jar:/home/alex/apps/scala-2.11.2/lib/scala-continuations-library_2.11-1.0.2.jar:/home/alex/apps/scala-2.11.2/lib/scala-continuations-plugin_2.11.2-1.0.2.jar:/home/alex/apps/scala-2.11.2/lib/scala-library.jar:/home/alex/apps/scala-2.11.2/lib/scalap-2.11.2.jar:/home/alex/apps/scala-2.11.2/lib/scala-parser-combinators_2.11-1.0.2.jar:/home/alex/apps/scala-2.11.2/lib/scala-reflect.jar:/home/alex/apps/scala-2.11.2/lib/scala-swing_2.11-1.0.1.jar:/home/alex/apps/scala-2.11.2/lib/scala-xml_2.11-1.0.2.jar -outxml -outjar /tmp/scalac-aspects.QkE6Hwdbd9/aspects.jar PerUnitTiming.aj
/home/alex/projects/scalac-aspects/PerUnitTiming.aj [error] The type java.util.Map$Entry cannot be resolved. It is indirectly referenced from required .class files
(no source information available)

1 error
```

They are for both JDK 7 and 8. What exact version of aspectj do you use?

**Comment by gkossakowski** [comment]
It looks like you have broken classpath for some reason. I tested it on Mac with AspectJ 1.7.1 and Java 7.

Did you try any basic AspectJ example to verify that your AspectJ installation is not broken?

**Comment by alexander-myltsev** [comment]
Yes, my installation was broken indeed. I used Java 8 that is incompatible.

I see your output prints per-phase timings. My only has `total`. I added 

``` diff
diff --git a/src/compiler/scala/tools/nsc/Global.scala b/src/compiler/scala/tools/nsc/Global.scala
index 572e579..7e34155 100644
--- a/src/compiler/scala/tools/nsc/Global.scala
+++ b/src/compiler/scala/tools/nsc/Global.scala
@@ -1616,6 +1616,7 @@ class Global(var currentSettings: Settings, var reporter: Reporter)
       symSource.keys foreach (x => resetPackageClass(x.owner))

       informTime("total", startTime)
+      inform(phaseTimings.table().toString)

       // Clear any sets or maps created via perRunCaches.
       perRunCaches.clearAll()
```

But compilation complains:

```
locker.comp:
    [mkdir] Created dir: /home/alex/apps/scala-src/build/locker/classes/compiler
[locker.compiler] Compiling 297 files to /home/alex/apps/scala-src/build/locker/classes/compiler
[locker.compiler] /home/alex/apps/scala-src/src/compiler/scala/tools/nsc/Global.scala:1618: error: not found: value phaseTimings
[locker.compiler]       inform(phaseTimings.table().toString)
[locker.compiler]              ^
[locker.compiler] one error found
```

What is the correct patch you made to your sources? 

---

Now I need to compile my pretty large project. We do it with SBT. Could you tell me how to get `scalac` launch command with all parameters and source files from `sbt compile`?

**Comment by gkossakowski** [comment]
Hi! I had some local changes to `PerUnitTiming` aspect that I forgot to commit and push. It's pushed now as 4e57d70f1add7248b0de02bf87c2652d9fd678b7. Now you should see per-phase and per-unit timings.

Have you tried `export compile` in sbt? That should give you all options that you need to pass to `scalac`.

**Comment by alexander-myltsev** [comment]
@gkossakowski everything works fine.

Optimizing my project. 

Thank you so much, Gregorz! Feel free to close this issue.

**Comment by gkossakowski** [comment]
Closing now. Let me know about your findings! I'd love to hear what were the inefficiencies you found.

**Comment by alexander-myltsev** [comment]
Our longest run is typer phase. I optimized all implicits -- i.e. explicitly told to compiler in imports what implicits I'd like to apply in scope. This seemed to improve compilation speed.

What do you suggest to read to understand what typer phase consist of, so we could optimize it more deeply?

**Comment by gkossakowski** [comment]
What fraction of total compilation time is spent in typer? Normally, it's about 25-33%.
How much time did you save by optimizing implicits?

**Comment by alexander-myltsev** [comment]
> What fraction of total compilation time is spent in typer? Normally, it's about 25-33%.

It is problematically to launch scalac in verbose mode as I get weird messages `in -1405254186977ms` as follows

```
[info] [loaded class file /home/ci/.ivy2/cache/io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.1.jar(spray/http/MessageChunk.class) in -1405254186977ms]
```

Do you know how to fix it?

> How much time did you save by optimizing implicits?

`sbt compile` before was about 30-35 secs. Now it is about 12-20 secs. Seems believable to you?

**Comment by alexander-myltsev** [comment]
Hi @gkossakowski 

I tested verbose compilation output on Win, MacOS, Ubuntu. All give me negative time (like typer in -1411958841319ms). How to interpret it if it makes sense?
